---
# tasks file for roles/docker
- name: Install python3 
  apt:
    pkg:
    - python3
  state: latest

- name: Install pip3
  apt:
    pkg: pip3
    state: present

- name: Install docker from pip3
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3