
BASE_OS = "ubuntu/bionic64"

Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "ansible-control",
      :box => BASE_OS,
      :ip => "10.200.123.198",
      :ssh_port => '2221'
    }
    # ,
    # {
    #   :hostname => "dev-srv",
    #   :box => BASE_OS,
    #   :ip => "192.168.0.65",
    #   :ssh_port => '2222'
    # },
    # {
    #   :hostname => "centurion",
    #   :box => BASE_OS,
    #   :ip => "192.168.0.66",
    #   :ssh_port => '2223'
    # }
  ]

  servers.each do |machine|

    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
    
      # node.vm.network :public_network, ip: machine[:ip]
      node.vm.network "public_network",
        bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter",
        ip: machine[:ip]

      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      # This step is because i run vagrant box on Windows and 
      # there is a problem with permissions to autogenerated keys
      # Please replace KEY string to your public key ;)
      node.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXYE3s7qh4hnI4B4+//YwZUm/l3yyjMbCaU9hwIPpzrL7OMfJ+brGsScWeo654z+Y5BPIaNCdpLy6BFq+WMNWth/Ls84Lsd/zR6fGiOJbiwIRh8e1CWwJaMz5cklPJM9YOGBc92dYaQisBRUyUhHFGUdomQufauMdWQ2bTczlCzlcJw78v8C55n+n7rjPG9GPIzbPfxXG4U1+EUlvEkZTfKpzT+EcVGcF0O4iVCb9dwpqgwH8zHnsye0ZYPASqPxKPiRRqwfhy1SBc7DIWigfVdSvUp/QDMDzF99urEDzXrTTg3t8LFPBHKg9fMMJ+rpoq1dCsHd1QGvywvci30YC3 dgryn@Damian" >> /home/vagrant/.ssh/authorized_keys
      SHELL

      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", machine[:hostname]]
      end
    end
  end

end