- name: Install common node.js, python libs
  apt:
    pkg:
    - nodejs
    - npm
    - git
    - python3-pip
    - python-pip
    - pwgen 
    - python3-docker  
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: yes